from django.db import models
from django.utils import timezone

class CommonInfo(models.Model):
    address1 = models.CharField(max_length=50, verbose_name="Address1")
    address2 = models.CharField(max_length=50, verbose_name="Address2")
    city = models.CharField(max_length=50, verbose_name="City")
    email = models.CharField(max_length=50, verbose_name="E-Mail")
    fax = models.CharField(max_length=50,verbose_name="Fax")
    phone = models.CharField(max_length=50, verbose_name="Phone")
    state = models.CharField(max_length=2, verbose_name="State")
    zip = models.CharField(max_length=5, verbose_name="Zip Code")

# Create three classes for dogs, cats, and unique
class Dog(CommonInfo):
    age = models.CharField(max_length=50, verbose_name="Age")
    animal = models.CharField(max_length=50, verbose_name="Animal")
    breeds = models.CharField(max_length=50, verbose_name="Breeds")
    contact = models.TextField(verbose_name="Contact")
    description = models.TextField(verbose_name="Description")
    catId = models.IntegerField(verbose_name="id", default=0)
    lastUpdate = models.DateTimeField(verbose_name="Date of Last Update", null=True, default=None, blank=True)
    media = models.TextField(verbose_name="Media")
    mix = models.CharField(max_length=50, verbose_name="Mix")
    name = models.CharField(max_length=50, verbose_name="Name")
    options = models.CharField(max_length=50, verbose_name="Options")
    sex = models.CharField(max_length=50, verbose_name="Sex")
    shelterId = models.CharField(max_length=50, verbose_name="ShelterID")
    shelterPetId = models.CharField(max_length=50, verbose_name="ShelterPetID")
    size = models.CharField(max_length=50, verbose_name="Size")
    status = models.CharField(max_length=50, verbose_name="Status")

class Cat(CommonInfo):
    age = models.CharField(max_length=50, verbose_name="Age")
    animal = models.CharField(max_length=50, verbose_name="Animal")
    breeds = models.CharField(max_length=50, verbose_name="Breeds")
    contact = models.TextField(verbose_name="Contact")
    description = models.TextField(verbose_name="Description")
    dogId = models.IntegerField(verbose_name="id", default=0)
    lastUpdate = models.DateTimeField(verbose_name="Date of Last Update", null=True, default=None, blank=True)
    media = models.TextField(verbose_name="Media")
    mix = models.CharField(max_length=50, verbose_name="Mix")
    name = models.CharField(max_length=50, verbose_name="Name")
    options = models.CharField(max_length=50, verbose_name="Options")
    sex = models.CharField(max_length=50, verbose_name="Sex")
    shelterId = models.CharField(max_length=50, verbose_name="ShelterID")
    shelterPetId = models.CharField(max_length=50, verbose_name="ShelterPetID")
    size = models.CharField(max_length=50, verbose_name="Size")
    status = models.CharField(max_length=50, verbose_name="Status")

class Unique(CommonInfo):
    age = models.CharField(max_length=50, verbose_name="Age")
    animal = models.CharField(max_length=50, verbose_name="Animal")
    breeds = models.CharField(max_length=50, verbose_name="Breeds")
    contact = models.TextField(verbose_name="Contact")
    description = models.TextField(verbose_name="Description")
    uniqueId = models.IntegerField(verbose_name="id", default=0)
    lastUpdate = models.DateTimeField(verbose_name="Date of Last Update", null=True, default=None, blank=True)
    media = models.TextField(verbose_name="Media")
    mix = models.CharField(max_length=50, verbose_name="Mix")
    name = models.CharField(max_length=50, verbose_name="Name")
    options = models.CharField(max_length=50, verbose_name="Options")
    sex = models.CharField(max_length=50, verbose_name="Sex")
    shelterId = models.CharField(max_length=50, verbose_name="ShelterID")
    shelterPetId = models.CharField(max_length=50, verbose_name="ShelterPetID")
    size = models.CharField(max_length=50, verbose_name="Size")
    status = models.CharField(max_length=50, verbose_name="Status")
